# Generated by Django 3.0.6 on 2020-05-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200525_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalborrow',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='term',
            field=models.PositiveIntegerField(default=0, help_text="Leave zero if it doesn't have term"),
        ),
        migrations.AlterField(
            model_name='historicalborrow',
            name='term',
            field=models.PositiveIntegerField(default=0, help_text="Leave zero if it doesn't have term"),
        ),
    ]
