# Generated by Django 3.0.6 on 2020-05-27 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200525_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Item'),
        ),
    ]
