# Generated by Django 3.0.6 on 2020-05-27 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200527_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendtermrequest',
            name='borrow',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Borrow'),
        ),
    ]
